### ISSUE TITLE
New to Rust, how do you get the value out of the response? 

### ISSUE THREAD

**Issue by EdwardDeaver** [angelodlfrtr/open-meteo-rs#10]
I'm running the example code in the readme and I can not figure out how to get the "temperature_2m_max" out of the "ForecastResultDaily" field. 

I can not get past " res.daily.expect("REASON").get(0)", I don't understand how get the value.

How do you get the value back?

**Comment by angelodlfrtr** [comment]
Hello @EdwardDeaver,

You can get the `ForecastResultItem` for `temperature_2m_max` with the following code :

```rust
res.daily
    .unwrap()
    .get(0)
    .unwrap()
    .values
    .get("temperature_2m_max")
    .unwrap()
```

This give you :

```rust
ForecastResultItem {
    unit: Some(
        "°C",
    ),
    value: Number(18.2),
}
```

You can get the value as f64 with the next snippet : 

```rust
let temp: f64 = res
    .daily
    .unwrap()
    .get(0)
    .unwrap()
    .values
    .get("temperature_2m_max")
    .unwrap()
    .value
    .as_f64()
    .unwrap();
```
